#!/usr/bin/env python3
"""
Seed Collector - 場所性が高い施設のシードデータを収集

Curated lists of historically and culturally significant facilities
in the Kanto region as the initial seed for Basho DB.
"""

import sqlite3
import json
import uuid
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "data" / "basho.db"


def get_db():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def gen_id():
    return f"f-{uuid.uuid4().hex[:12]}"


def insert_facility(conn, data: dict):
    """Insert a facility, skip if URL already exists."""
    if data.get("url"):
        existing = conn.execute("SELECT id FROM facilities WHERE url = ?", (data["url"],)).fetchone()
        if existing:
            return None

    fid = gen_id()
    conn.execute("""
        INSERT INTO facilities (id, name, name_kana, category, subcategory, url, address,
                                prefecture, city, overview, features, founded_year,
                                cultural_designation, source_type, source_url)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        fid,
        data.get("name", ""),
        data.get("name_kana", ""),
        data.get("category", "other"),
        data.get("subcategory", ""),
        data.get("url", ""),
        data.get("address", ""),
        data.get("prefecture", ""),
        data.get("city", ""),
        data.get("overview", ""),
        json.dumps(data.get("features", []), ensure_ascii=False),
        data.get("founded_year"),
        data.get("cultural_designation", ""),
        data.get("source_type", "manual"),
        data.get("source_url", ""),
    ))
    return fid


# === Curated Seed Data ===
# Eastern Japan (Tokyo / Kanto) - historically and culturally significant facilities

SEED_DATA = [
    # --- Classic Hotels ---
    {
        "name": "東京ステーションホテル",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.tokyostationhotel.jp/",
        "address": "東京都千代田区丸の内1-9-1",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1915年開業。辰野金吾設計の東京駅丸の内駅舎内に位置するクラシックホテル。国の重要文化財である赤レンガ駅舎を活用。",
        "features": ["クラシックホテル", "重要文化財", "辰野金吾設計", "1915年開業"],
        "founded_year": 1915,
        "cultural_designation": "important_cultural_property",
        "source_type": "manual",
    },
    {
        "name": "帝国ホテル 東京",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.imperialhotel.co.jp/",
        "address": "東京都千代田区内幸町1-1-1",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1890年開業。日本を代表するクラシックホテル。フランク・ロイド・ライトによる旧本館（ライト館）で世界的に知られる。日本のホテル文化の礎。",
        "features": ["クラシックホテル", "1890年開業", "フランク・ロイド・ライト", "日本のホテル文化の礎"],
        "founded_year": 1890,
        "source_type": "manual",
    },
    {
        "name": "ホテルニューグランド",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.hotel-newgrand.co.jp/",
        "address": "神奈川県横浜市中区山下町10",
        "prefecture": "神奈川県",
        "city": "横浜市",
        "overview": "1927年開業。横浜・山下公園前に建つクラシックホテル。マッカーサーが滞在した315号室、ナポリタン・ドリア・プリンアラモード発祥の地。",
        "features": ["クラシックホテル", "1927年開業", "横浜", "洋食発祥", "マッカーサー"],
        "founded_year": 1927,
        "source_type": "manual",
    },
    {
        "name": "富士屋ホテル",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.fujiyahotel.jp/",
        "address": "神奈川県足柄下郡箱根町宮ノ下359",
        "prefecture": "神奈川県",
        "city": "箱根町",
        "overview": "1878年開業。日本初の本格的リゾートホテル。和洋折衷の独特な建築様式。チャップリン、ヘレン・ケラーなど多くの著名人が宿泊。登録有形文化財。",
        "features": ["クラシックホテル", "1878年開業", "箱根", "和洋折衷建築", "登録有形文化財"],
        "founded_year": 1878,
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
    {
        "name": "日光金谷ホテル",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.kanayahotel.co.jp/nkh/",
        "address": "栃木県日光市上鉢石町1300",
        "prefecture": "栃木県",
        "city": "日光市",
        "overview": "1873年開業。現存する日本最古のクラシックリゾートホテル。日光東照宮近くに位置し、国の登録有形文化財。百年カレーが名物。",
        "features": ["クラシックホテル", "1873年開業", "日本最古", "日光", "登録有形文化財"],
        "founded_year": 1873,
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
    {
        "name": "万平ホテル",
        "category": "hotel",
        "subcategory": "classic_hotel",
        "url": "https://www.mampei.co.jp/",
        "address": "長野県北佐久郡軽井沢町軽井沢925",
        "prefecture": "長野県",
        "city": "軽井沢町",
        "overview": "1894年開業（旅籠としては1764年）。軽井沢を代表するクラシックホテル。ジョン・レノン一家が毎夏滞在したことでも知られる。",
        "features": ["クラシックホテル", "1894年開業", "軽井沢", "ジョン・レノン", "避暑地文化"],
        "founded_year": 1894,
        "source_type": "manual",
    },

    # --- Historic Ryokan ---
    {
        "name": "強羅花壇",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "https://www.gorakadan.com/",
        "address": "神奈川県足柄下郡箱根町強羅1300",
        "prefecture": "神奈川県",
        "city": "箱根町",
        "overview": "旧閑院宮別邸跡地に建つ温泉旅館。皇族の別荘地としての歴史を継承し、庭園と建築に格調高い場所性を持つ。",
        "features": ["温泉旅館", "箱根", "旧皇族別邸", "庭園"],
        "source_type": "manual",
    },
    {
        "name": "あさば",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "https://www.asaba-ryokan.com/",
        "address": "静岡県伊豆市修善寺3450-1",
        "prefecture": "静岡県",
        "city": "伊豆市",
        "overview": "1489年創業。修善寺温泉にある老舗旅館。能舞台を持つ庭園が特徴的。500年以上の歴史を持つ日本を代表する旅館の一つ。",
        "features": ["温泉旅館", "1489年創業", "修善寺", "能舞台", "老舗"],
        "founded_year": 1489,
        "source_type": "manual",
    },
    {
        "name": "俵屋旅館",
        "category": "ryokan",
        "subcategory": "traditional_ryokan",
        "url": "https://www.tawaraya.co.jp/",
        "address": "京都府京都市中京区麩屋町通姉小路上ル中白山町278",
        "prefecture": "京都府",
        "city": "京都市",
        "overview": "1704年創業。京都を代表する老舗旅館。スティーブ・ジョブズが定宿としたことでも知られる。日本旅館の美意識の極致。",
        "features": ["老舗旅館", "1704年創業", "京都", "スティーブ・ジョブズ", "日本旅館の極致"],
        "founded_year": 1704,
        "source_type": "manual",
    },
    {
        "name": "柊家",
        "category": "ryokan",
        "subcategory": "traditional_ryokan",
        "url": "https://www.hiiragiya.co.jp/",
        "address": "京都府京都市中京区麩屋町通姉小路上ル聚楽町",
        "prefecture": "京都府",
        "city": "京都市",
        "overview": "1818年創業。京都御所近くに位置する老舗旅館。川端康成、三島由紀夫など文豪に愛された。「来者如帰」の精神。",
        "features": ["老舗旅館", "1818年創業", "京都", "文豪の宿", "来者如帰"],
        "founded_year": 1818,
        "source_type": "manual",
    },
    {
        "name": "法師",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "https://www.ho-shi.co.jp/",
        "address": "石川県小松市粟津温泉",
        "prefecture": "石川県",
        "city": "小松市",
        "overview": "718年創業。世界最古級の旅館。1300年以上の歴史を持つ粟津温泉の老舗。46代にわたり家族経営を続ける。",
        "features": ["温泉旅館", "718年創業", "世界最古級", "粟津温泉", "46代"],
        "founded_year": 718,
        "source_type": "manual",
    },
    {
        "name": "慶雲館",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "https://www.keiunkan.co.jp/",
        "address": "山梨県南巨摩郡早川町湯島",
        "prefecture": "山梨県",
        "city": "早川町",
        "overview": "705年創業。ギネス世界記録に認定された世界最古の宿泊施設。西山温泉にある秘湯の宿。1300年以上の歴史。",
        "features": ["温泉旅館", "705年創業", "ギネス世界記録", "世界最古", "西山温泉", "秘湯"],
        "founded_year": 705,
        "source_type": "manual",
    },

    # --- Historic Restaurants (Tokyo) ---
    {
        "name": "神田まつや",
        "category": "restaurant_japanese",
        "subcategory": "soba",
        "url": "https://www.kanda-matsuya.jp/",
        "address": "東京都千代田区神田須田町1-13",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1884年創業。神田の老舗蕎麦屋。登録有形文化財の木造建築で、池波正太郎が愛した蕎麦屋として知られる。",
        "features": ["蕎麦", "1884年創業", "老舗", "登録有形文化財", "池波正太郎"],
        "founded_year": 1884,
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
    {
        "name": "竹むら",
        "category": "restaurant_japanese",
        "subcategory": "wagashi",
        "url": "",
        "address": "東京都千代田区神田須田町1-19",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1930年創業。神田須田町の甘味処。戦前の木造建築が残る登録有形文化財。揚げまんじゅうが名物。",
        "features": ["甘味処", "1930年創業", "登録有形文化財", "木造建築", "揚げまんじゅう"],
        "founded_year": 1930,
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
    {
        "name": "いせ源",
        "category": "restaurant_japanese",
        "subcategory": "anko",
        "url": "https://www.isegen.com/",
        "address": "東京都千代田区神田須田町1-11-1",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1830年創業。あんこう料理専門店。神田須田町に残る木造建築で営業を続ける。東京に残る希少な江戸の食文化。",
        "features": ["あんこう料理", "1830年創業", "老舗", "木造建築", "江戸の食文化"],
        "founded_year": 1830,
        "source_type": "manual",
    },
    {
        "name": "ぼたん",
        "category": "restaurant_japanese",
        "subcategory": "tori_sukiyaki",
        "url": "",
        "address": "東京都千代田区神田須田町1-15",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1897年創業。鳥すきやき専門店。神田須田町の老舗街に位置し、登録有形文化財の建物で鳥すき一筋。",
        "features": ["鳥すきやき", "1897年創業", "老舗", "登録有形文化財", "神田須田町"],
        "founded_year": 1897,
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
    {
        "name": "駒形どぜう",
        "category": "restaurant_japanese",
        "subcategory": "dojo",
        "url": "https://www.dozeu.com/",
        "address": "東京都台東区駒形1-7-12",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1801年創業。どじょう料理の老舗。江戸時代から続く庶民の味を守り続ける。下町文化を体現する場。",
        "features": ["どじょう料理", "1801年創業", "老舗", "江戸の味", "下町文化"],
        "founded_year": 1801,
        "source_type": "manual",
    },
    {
        "name": "室町砂場",
        "category": "restaurant_japanese",
        "subcategory": "soba",
        "url": "https://www.muromachi-sunaba.co.jp/",
        "address": "東京都中央区日本橋室町4-1-13",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1869年創業。日本橋の老舗蕎麦屋。天もり（天ぷらそば）発祥の店。江戸蕎麦の三大系統「砂場」の流れを汲む。",
        "features": ["蕎麦", "1869年創業", "老舗", "天もり発祥", "砂場系", "日本橋"],
        "founded_year": 1869,
        "source_type": "manual",
    },
    {
        "name": "尾張屋",
        "category": "restaurant_japanese",
        "subcategory": "soba",
        "url": "https://www.owariya.co.jp/",
        "address": "京都府京都市中京区車屋町通二条下ル",
        "prefecture": "京都府",
        "city": "京都市",
        "overview": "1465年創業。京都最古の蕎麦屋。元は菓子司として創業し、江戸中期に蕎麦を始めた。御所御用達の歴史。",
        "features": ["蕎麦", "1465年創業", "京都最古", "御所御用達", "老舗"],
        "founded_year": 1465,
        "source_type": "manual",
    },
    {
        "name": "鯛めし 日本橋 玉ゐ",
        "category": "restaurant_japanese",
        "subcategory": "anago",
        "url": "https://www.tamai.info/",
        "address": "東京都中央区日本橋2-9-9",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "築80年以上の日本橋の路地裏に佇む穴子料理専門店。江戸前の食文化を現代に伝える。建物の佇まいが場所性を体現。",
        "features": ["穴子料理", "日本橋", "路地裏", "築80年建築", "江戸前"],
        "source_type": "manual",
    },
    {
        "name": "煉瓦亭",
        "category": "restaurant_western",
        "subcategory": "yoshoku",
        "url": "https://www.renga-tei.com/",
        "address": "東京都中央区銀座3-5-16",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1895年創業。銀座の洋食店。ポークカツレツ（とんかつ）、オムライス、エビフライの発祥店とされる。日本の洋食文化の原点。",
        "features": ["洋食", "1895年創業", "銀座", "とんかつ発祥", "オムライス発祥", "洋食文化の原点"],
        "founded_year": 1895,
        "source_type": "manual",
    },
    {
        "name": "資生堂パーラー",
        "category": "restaurant_western",
        "subcategory": "yoshoku",
        "url": "https://parlour.shiseido.co.jp/",
        "address": "東京都中央区銀座8-8-3 東京銀座資生堂ビル",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1902年ソーダファウンテンとして開業。資生堂の美意識と銀座の文化が融合した場所。ミートクロケット、アイスクリームソーダなど銀座文化の象徴。",
        "features": ["洋食", "1902年開業", "銀座", "資生堂", "銀座文化の象徴"],
        "founded_year": 1902,
        "source_type": "manual",
    },

    # --- Historic Cafes ---
    {
        "name": "カフェ・ド・ランブル",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "",
        "address": "東京都中央区銀座8-10-15",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1948年創業。銀座の名喫茶。オールドコーヒーの先駆者・関口一郎が開いた純喫茶。自家焙煎にこだわり続ける珈琲の聖地。",
        "features": ["喫茶店", "1948年創業", "銀座", "自家焙煎", "オールドコーヒー"],
        "founded_year": 1948,
        "source_type": "manual",
    },
    {
        "name": "珈琲 天国",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "",
        "address": "東京都台東区浅草1-41-9",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "浅草の純喫茶。「天国」の焼印が押されたホットケーキが名物。昭和の喫茶店文化を色濃く残す空間。",
        "features": ["喫茶店", "浅草", "昭和レトロ", "ホットケーキ"],
        "source_type": "manual",
    },
    {
        "name": "アンヂェラス",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "",
        "address": "東京都台東区浅草1-17-6（閉店）",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1946年創業、2019年閉店。浅草を代表した純喫茶。手塚治虫、池波正太郎など多くの文化人に愛された。梅ダッチコーヒーが名物だった。記録として保存。",
        "features": ["喫茶店", "1946年創業", "浅草", "閉店", "文化人の溜まり場", "記録保存"],
        "founded_year": 1946,
        "source_type": "manual",
    },
    {
        "name": "KAYABA珈琲",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "https://kayaba-coffee.com/",
        "address": "東京都台東区谷中6-1-29",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1938年築の出桁造り町家を活用した喫茶店。2009年に地域の有志によりリノベーション再生。谷根千の下町文化を体現。",
        "features": ["喫茶店", "1938年築", "出桁造り", "谷根千", "リノベーション", "下町文化"],
        "founded_year": 1938,
        "source_type": "manual",
    },

    # --- Kanto area historic restaurants ---
    {
        "name": "鉢の木",
        "category": "restaurant_japanese",
        "subcategory": "kaiseki",
        "url": "https://www.hachinoki.co.jp/",
        "address": "神奈川県鎌倉市山ノ内7",
        "prefecture": "神奈川県",
        "city": "鎌倉市",
        "overview": "鎌倉・北鎌倉に位置する精進料理店。建長寺門前で禅の精神を体現した精進料理を提供。鎌倉の歴史文化と一体の場所。",
        "features": ["精進料理", "鎌倉", "北鎌倉", "建長寺", "禅"],
        "source_type": "manual",
    },
    {
        "name": "鎌倉 御代川",
        "category": "restaurant_japanese",
        "subcategory": "kaiseki",
        "url": "https://www.miyokawa.co.jp/",
        "address": "神奈川県鎌倉市大船1-24-20",
        "prefecture": "神奈川県",
        "city": "鎌倉市",
        "overview": "1949年創業。鎌倉の懐石料理店。地元の食材と鎌倉の四季を活かした料理。古都鎌倉の食文化を継承。",
        "features": ["懐石料理", "1949年創業", "鎌倉", "地産地消"],
        "founded_year": 1949,
        "source_type": "manual",
    },

    # --- Tokyo historic Western-influenced ---
    {
        "name": "レストラン・クレッセント",
        "category": "restaurant_western",
        "subcategory": "french",
        "url": "",
        "address": "東京都港区南青山5-3-2（閉店）",
        "prefecture": "東京都",
        "city": "港区",
        "overview": "1925年築のアール・デコ様式洋館で営業していたフランス料理店。日本におけるフランス料理受容の歴史的場所。記録として保存。",
        "features": ["フランス料理", "1925年築", "アール・デコ", "閉店", "記録保存"],
        "founded_year": 1925,
        "source_type": "manual",
    },
    {
        "name": "小笠原伯爵邸",
        "category": "restaurant_western",
        "subcategory": "spanish",
        "url": "https://www.ogasawaratei.com/",
        "address": "東京都新宿区河田町10-10",
        "prefecture": "東京都",
        "city": "新宿区",
        "overview": "1927年築の旧小笠原伯爵邸をレストランに転用。スパニッシュ様式の邸宅建築。東京都指定有形文化財。イスラム風のタイルや内装が特徴的。",
        "features": ["スペイン料理", "1927年築", "旧伯爵邸", "東京都有形文化財", "スパニッシュ様式"],
        "founded_year": 1927,
        "cultural_designation": "tokyo_tangible",
        "source_type": "manual",
    },

    # --- More Tokyo/Kanto historic restaurants ---
    {
        "name": "やげん堀 中島商店",
        "category": "restaurant_japanese",
        "subcategory": "spice",
        "url": "https://www.yagenbori.jp/",
        "address": "東京都台東区浅草橋3-36-2（本店）",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1625年創業。七味唐辛子の老舗。漢方薬の調合技術を応用した七味の元祖。400年近い歴史を持つ江戸の食文化。",
        "features": ["七味唐辛子", "1625年創業", "江戸の食文化", "漢方", "老舗"],
        "founded_year": 1625,
        "source_type": "manual",
    },
    {
        "name": "梅園",
        "category": "restaurant_japanese",
        "subcategory": "wagashi",
        "url": "https://www.asakusa-umezono.co.jp/",
        "address": "東京都台東区浅草1-31-12",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1854年創業。浅草の甘味処。あわぜんざいの元祖。安政年間から浅草の甘味文化を支え続ける。",
        "features": ["甘味処", "1854年創業", "浅草", "あわぜんざい", "老舗"],
        "founded_year": 1854,
        "source_type": "manual",
    },
    {
        "name": "大黒家天麩羅",
        "category": "restaurant_japanese",
        "subcategory": "tempura",
        "url": "https://www.tempura.co.jp/",
        "address": "東京都台東区浅草1-38-10",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1887年創業。浅草の老舗天ぷら専門店。ごま油100%で揚げる江戸前天ぷらの伝統を守り続ける。",
        "features": ["天ぷら", "1887年創業", "浅草", "ごま油", "江戸前"],
        "founded_year": 1887,
        "source_type": "manual",
    },
    {
        "name": "伊勢廣",
        "category": "restaurant_japanese",
        "subcategory": "yakitori",
        "url": "https://www.isehiro.co.jp/",
        "address": "東京都中央区京橋1-1-1",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1921年創業。京橋の老舗焼鳥店。備長炭で一本一本丁寧に焼き上げる。東京の焼鳥文化を代表する名店。",
        "features": ["焼鳥", "1921年創業", "京橋", "備長炭", "老舗"],
        "founded_year": 1921,
        "source_type": "manual",
    },
    {
        "name": "人形町 今半",
        "category": "restaurant_japanese",
        "subcategory": "sukiyaki",
        "url": "https://www.imahan.com/",
        "address": "東京都中央区日本橋人形町2-9-12",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1895年創業。人形町の老舗すき焼き店。明治から続く牛鍋文化の継承者。下町の粋と食文化を体現。",
        "features": ["すき焼き", "1895年創業", "人形町", "牛鍋文化", "老舗"],
        "founded_year": 1895,
        "source_type": "manual",
    },
    {
        "name": "たいめいけん",
        "category": "restaurant_western",
        "subcategory": "yoshoku",
        "url": "https://www.taimeiken.co.jp/",
        "address": "東京都中央区日本橋1-12-10",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1931年創業。日本橋の老舗洋食店。タンポポオムライスで知られる。日本の洋食文化を牽引してきた名店。",
        "features": ["洋食", "1931年創業", "日本橋", "オムライス", "洋食文化"],
        "founded_year": 1931,
        "source_type": "manual",
    },

    # --- Historic inns and minshuku ---
    {
        "name": "鶴巻温泉 元湯 陣屋",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "https://www.jinya-inn.com/",
        "address": "神奈川県秦野市鶴巻北2-8-24",
        "prefecture": "神奈川県",
        "city": "秦野市",
        "overview": "1918年創業。将棋・囲碁の対局場としても知られる老舗旅館。棋士たちの歴史が刻まれた場所。日本庭園が美しい。",
        "features": ["温泉旅館", "1918年創業", "将棋・囲碁の対局場", "日本庭園"],
        "founded_year": 1918,
        "source_type": "manual",
    },

    # --- More diverse Tokyo spots ---
    {
        "name": "みかわ 是山居",
        "category": "restaurant_japanese",
        "subcategory": "tempura",
        "url": "",
        "address": "東京都江東区福住1-3-1",
        "prefecture": "東京都",
        "city": "江東区",
        "overview": "天ぷら職人・早乙女哲哉の店。深川の蔵を改装した空間で、江戸前天ぷらの極致を追求。職人の身体知が凝縮された場所。",
        "features": ["天ぷら", "深川", "蔵改装", "職人技", "江戸前"],
        "source_type": "manual",
    },
    {
        "name": "鍵善良房",
        "category": "restaurant_japanese",
        "subcategory": "wagashi",
        "url": "https://www.kagizen.co.jp/",
        "address": "京都府京都市東山区祇園町南側570-210",
        "prefecture": "京都府",
        "city": "京都市",
        "overview": "1001年創業とされる京都の老舗和菓子店。祇園に位置し、くずきりが名物。千年以上の歴史を持つ日本菓子文化の象徴。",
        "features": ["和菓子", "1001年創業", "祇園", "くずきり", "千年の歴史"],
        "founded_year": 1001,
        "source_type": "manual",
    },
    {
        "name": "虎屋",
        "category": "restaurant_japanese",
        "subcategory": "wagashi",
        "url": "https://www.toraya-group.co.jp/",
        "address": "東京都港区赤坂4-9-22",
        "prefecture": "東京都",
        "city": "港区",
        "overview": "室町後期（1520年頃）京都で創業。御所御用達の和菓子店。500年の歴史を持ち、和菓子文化の最高峰。赤坂本店は内藤廣設計の現代建築と伝統の融合。",
        "features": ["和菓子", "1520年頃創業", "御所御用達", "赤坂", "内藤廣設計"],
        "founded_year": 1520,
        "source_type": "manual",
    },

    # --- Kominka / Renovated Historic Buildings ---
    {
        "name": "上野桜木あたり",
        "category": "restaurant_cafe",
        "subcategory": "complex",
        "url": "https://uenosakuragiatari.jp/",
        "address": "東京都台東区上野桜木2-15-6",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1938年築の3軒の古民家をリノベーションした複合施設。ビアホール、パン屋、オリーブオイル店が入る。谷根千エリアの場所性を凝縮。",
        "features": ["古民家リノベ", "1938年築", "複合施設", "谷根千", "ビアホール"],
        "founded_year": 1938,
        "source_type": "manual",
    },
    {
        "name": "HAGISO",
        "category": "restaurant_cafe",
        "subcategory": "complex",
        "url": "https://hagiso.jp/",
        "address": "東京都台東区谷中3-10-25",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1955年築の木造アパートをリノベーション。カフェ、ギャラリー、宿泊（hanare）を含む「最小文化複合施設」。まちやどの概念を実践。",
        "features": ["カフェ", "木造アパート改装", "最小文化複合施設", "谷中", "まちやど"],
        "founded_year": 1955,
        "source_type": "manual",
    },

    # --- Unique Kanto spots ---
    {
        "name": "自由学園 明日館",
        "category": "restaurant_cafe",
        "subcategory": "cafe",
        "url": "https://jiyu.jp/",
        "address": "東京都豊島区西池袋2-31-3",
        "prefecture": "東京都",
        "city": "豊島区",
        "overview": "1921年、フランク・ロイド・ライト設計の校舎を活用したカフェ・イベント空間。重要文化財。大正自由教育の精神が宿る場所。",
        "features": ["カフェ", "1921年築", "フランク・ロイド・ライト", "重要文化財", "自由教育"],
        "founded_year": 1921,
        "cultural_designation": "important_cultural_property",
        "source_type": "manual",
    },
    {
        "name": "旧岩崎邸庭園",
        "category": "restaurant_cafe",
        "subcategory": "cafe",
        "url": "https://www.tokyo-park.or.jp/park/iwasaki/",
        "address": "東京都台東区池之端1-3-45",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1896年、ジョサイア・コンドル設計の洋館。三菱財閥・岩崎家の本邸。重要文化財。併設カフェで庭園を望みながらの喫茶が可能。",
        "features": ["カフェ", "1896年築", "ジョサイア・コンドル", "重要文化財", "三菱岩崎家"],
        "founded_year": 1896,
        "cultural_designation": "important_cultural_property",
        "source_type": "manual",
    },
    {
        "name": "アロマ珈琲",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "",
        "address": "東京都千代田区神田神保町1-4",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1955年創業。神保町の古書店街に佇む純喫茶。自家焙煎珈琲とクラシック音楽。古書と珈琲の文化が交差する場所。",
        "features": ["喫茶店", "1955年創業", "神保町", "古書店街", "自家焙煎", "クラシック音楽"],
        "founded_year": 1955,
        "source_type": "manual",
    },
    {
        "name": "さぼうる",
        "category": "restaurant_cafe",
        "subcategory": "kissaten",
        "url": "",
        "address": "東京都千代田区神田神保町1-11",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1955年創業。神保町の名物喫茶店。山小屋風の内装、ナポリタンが名物。出版・文学関係者の溜まり場として知られる。",
        "features": ["喫茶店", "1955年創業", "神保町", "山小屋風", "文学関係者"],
        "founded_year": 1955,
        "source_type": "manual",
    },

    # --- Historic Unagi/Sushi ---
    {
        "name": "野田岩",
        "category": "restaurant_japanese",
        "subcategory": "unagi",
        "url": "https://www.nodaiwa.co.jp/",
        "address": "東京都港区東麻布1-5-4",
        "prefecture": "東京都",
        "city": "港区",
        "overview": "1830年創業。200年近い歴史を持つ鰻の老舗。五代目が守る江戸前の焼き技法。パリにも出店した和食文化の伝承者。",
        "features": ["鰻", "1830年創業", "麻布", "江戸前", "五代目", "老舗"],
        "founded_year": 1830,
        "source_type": "manual",
    },
    {
        "name": "すきやばし次郎",
        "category": "restaurant_japanese",
        "subcategory": "sushi",
        "url": "",
        "address": "東京都中央区銀座4-2-15 塚本総業ビルB1",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "小野二郎の鮨。ミシュラン三ツ星。カウンター10席のみ。職人の身体知と技の極致。オバマ大統領の訪問で世界的に知られる。",
        "features": ["寿司", "銀座", "ミシュラン三ツ星", "職人技の極致", "カウンター10席"],
        "source_type": "manual",
    },

    # --- Kanto Historical Buildings used as restaurants ---
    {
        "name": "松本楼",
        "category": "restaurant_western",
        "subcategory": "french",
        "url": "https://www.matsumotoro.co.jp/",
        "address": "東京都千代田区日比谷公園1-2",
        "prefecture": "東京都",
        "city": "千代田区",
        "overview": "1903年創業。日比谷公園内の老舗レストラン。孫文、ヘレン・ケラーなど歴史的人物が訪れた。10円カレーの日で知られる。",
        "features": ["フランス料理", "1903年創業", "日比谷公園", "歴史的人物", "10円カレー"],
        "founded_year": 1903,
        "source_type": "manual",
    },
    {
        "name": "三國屋",
        "category": "restaurant_japanese",
        "subcategory": "soba",
        "url": "",
        "address": "東京都文京区本駒込6-16-11",
        "prefecture": "東京都",
        "city": "文京区",
        "overview": "築100年以上の木造建築で営業する蕎麦屋。六義園近くに位置し、下町の日常と歴史が溶け合った場所。",
        "features": ["蕎麦", "築100年", "木造建築", "六義園", "下町"],
        "source_type": "manual",
    },

    # --- Fill to 50+ with more Kanto selections ---
    {
        "name": "割烹 中嶋",
        "category": "restaurant_japanese",
        "subcategory": "kappo",
        "url": "",
        "address": "東京都新宿区新宿3-32-5",
        "prefecture": "東京都",
        "city": "新宿区",
        "overview": "新宿の割烹料理店。ミシュラン一つ星。昼のいわしの定食が名物。新宿という喧騒の中に凛とした和の空間を保つ。",
        "features": ["割烹", "新宿", "ミシュラン一つ星", "いわし", "和の空間"],
        "source_type": "manual",
    },
    {
        "name": "鷹の巣",
        "category": "ryokan",
        "subcategory": "onsen_ryokan",
        "url": "",
        "address": "栃木県那須塩原市湯本塩原",
        "prefecture": "栃木県",
        "city": "那須塩原市",
        "overview": "塩原温泉の秘湯の宿。渓谷沿いに建つ一軒宿。自然と一体化した場所性を持つ温泉旅館。",
        "features": ["温泉旅館", "塩原温泉", "秘湯", "渓谷", "一軒宿"],
        "source_type": "manual",
    },
    {
        "name": "日本橋 お多幸本店",
        "category": "restaurant_japanese",
        "subcategory": "oden",
        "url": "https://www.otako.co.jp/",
        "address": "東京都中央区日本橋2-2-3",
        "prefecture": "東京都",
        "city": "中央区",
        "overview": "1923年創業。日本橋のおでん専門店。関東炊きの伝統を守る。とうめしが名物。大正から続く庶民の味。",
        "features": ["おでん", "1923年創業", "日本橋", "関東炊き", "とうめし"],
        "founded_year": 1923,
        "source_type": "manual",
    },
    {
        "name": "並木藪蕎麦",
        "category": "restaurant_japanese",
        "subcategory": "soba",
        "url": "",
        "address": "東京都台東区雷門2-11-9",
        "prefecture": "東京都",
        "city": "台東区",
        "overview": "1913年創業。浅草の老舗蕎麦屋。藪蕎麦の系統。辛めのつゆと細打ちの蕎麦。浅草の食文化を体現する場所。",
        "features": ["蕎麦", "1913年創業", "浅草", "藪蕎麦系", "老舗"],
        "founded_year": 1913,
        "source_type": "manual",
    },
    {
        "name": "はん亭",
        "category": "restaurant_japanese",
        "subcategory": "kushiage",
        "url": "https://www.hantei.co.jp/",
        "address": "東京都文京区根津2-12-15",
        "prefecture": "東京都",
        "city": "文京区",
        "overview": "築90年以上の三階建て木造家屋で営業する串揚げ店。登録有形文化財。根津の下町風情を凝縮した場所。",
        "features": ["串揚げ", "築90年", "三階建て木造", "登録有形文化財", "根津"],
        "cultural_designation": "registered_tangible",
        "source_type": "manual",
    },
]


def main():
    conn = get_db()
    inserted = 0
    skipped = 0

    for data in SEED_DATA:
        fid = insert_facility(conn, data)
        if fid:
            inserted += 1
        else:
            skipped += 1

    conn.commit()
    total = conn.execute("SELECT COUNT(*) FROM facilities").fetchone()[0]
    conn.close()

    print(f"Seed collection complete:")
    print(f"  Inserted: {inserted}")
    print(f"  Skipped (duplicate): {skipped}")
    print(f"  Total facilities in DB: {total}")


if __name__ == "__main__":
    main()
